Hw
mrmax24/book-store pull request #2
Opened 2024-02-23 15:34 UTC by mrmax24

2024-02-23 18:48 UTC, MentorMA approved these changes

2024-02-29 14:27 UTC, MentorMA requested changes

2024-02-29 14:27 UTC, MentorMA commented on src/main/java/mate/academy/bookstore/model/Book.java
> +}
Keep one style between fields

2024-02-29 14:27 UTC, MentorMA commented on src/main/java/mate/academy/bookstore/model/Book.java
> +}
![image](https://github.com/mrmax24/book-store/assets/156338484/ee62c78e-e448-466b-a148-a49d2f50b6f1)

2024-02-29 19:05 UTC, okuzan requested changes

2024-02-29 19:05 UTC, okuzan commented on src/main/java/mate/academy/bookstore/config/MapperConfig.java
> +
```suggestion
)
```

2024-02-29 19:05 UTC, okuzan commented on src/main/java/mate/academy/bookstore/model/Book.java
> +@Where(clause = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_deleted = TRUE WHERE id = ?")
@Where(clause = "is_deleted = FALSE")
```

2024-02-29 19:05 UTC, okuzan commented on src/main/java/mate/academy/bookstore/model/Book.java
> +
```suggestion
```
no empty lines after method/class definition are required

2024-03-01 14:17 UTC, merged